CHUNK_SIZE = 300
CHUNK_OVERLAP = 60

EMBEDDING_MODEL = "gemini-embedding-001"
CHAT_MODEL = "gemini-2.5-flash"

FAISS_PATH = "faiss-db"

DIMENSION = 3072
NEIGHBORS = 32

DEFAULT_TEMPERATURE = 0.7
MAX_TEMPERATURE = 2.0
MIN_TEMPERATURE = 0

KWARGS = 2

MIN = 5
MAX = 1000

SESSION_ID = "Default_Session"